[package]
name = "tracing-journald"
version = "0.3.2"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage = "https://tokio.rs"
description = "rich journald subscriber for `tracing`"
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
]
keywords = ["tracing", "journald"]
rust-version.workspace = true

[dependencies]
libc = { workspace = true }
tracing-core = { workspace = true, default-features = true }
tracing-subscriber = { workspace = true, features = ["registry"] }

[dev-dependencies]
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true, default-features = true }

[lints]
workspace = true
