//! Spans represent periods of time in the execution of a program.

use core::num::NonZeroU64;

use crate::Metadata;
use crate::Parent;
use crate::field;
use crate::field::FieldSet;

/// Identifies a span within the context of a subscriber.
///
/// They are generated by [`Subscriber`]s for each span as it is created, by
/// the [`new_span`] trait method. See the documentation for that method for
/// more information on span ID generation.
///
/// [`Subscriber`]: super::subscriber::Subscriber
/// [`new_span`]: super::subscriber::Subscriber::new_span
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct Id(NonZeroU64);

/// Attributes provided to a `Subscriber` describing a new span when it is
/// created.
#[derive(Debug)]
pub struct Attributes<'a> {
  /// Metadata describing the callsite that created the span.
  metadata: &'static Metadata<'static>,
  /// Values recorded with the span at creation time.
  values:   &'a field::ValueSet<'a>,
  /// Parent relationship requested for the new span.
  parent:   Parent,
}

/// A set of fields recorded by a span.
#[derive(Debug)]
pub struct Record<'a> {
  /// Values recorded against an existing span.
  values: &'a field::ValueSet<'a>,
}

/// Indicates what [the `Subscriber` considers] the "current" span.
///
/// As subscribers may not track a notion of a current span, this has three
/// possible states:
/// - "unknown", indicating that the subscriber does not track a current span,
/// - "none", indicating that the current context is known to not be in a span,
/// - "some", with the current span's [`Id`] and [`Metadata`].
///
/// [the `Subscriber` considers]: super::subscriber::Subscriber::current_span
/// [`Metadata`]: super::metadata::Metadata
#[derive(Debug)]
pub struct Current {
  /// Internal representation of the current-span state.
  inner: CurrentInner,
}

/// Internal states for the current span reported by a subscriber.
#[derive(Debug)]
enum CurrentInner {
  /// The subscriber knows a current span.
  Current {
    /// Identifier for the current span.
    id:       Id,
    /// Metadata for the current span.
    metadata: &'static Metadata<'static>,
  },
  /// The subscriber knows there is no current span.
  None,
  /// The subscriber does not track the current span.
  Unknown,
}

// ===== impl Span =====

impl Id {
  /// Attempts to construct a new span ID from the given `u64`.
  ///
  /// Returns `None` if the provided `u64` is 0.
  #[must_use]
  pub const fn try_from_u64(raw: u64) -> Option<Self> {
    let Some(id) = NonZeroU64::new(raw) else {
      return None;
    };
    Some(Self(id))
  }

  /// Constructs a new span ID from the given `NonZeroU64`.
  #[allow(
    clippy::single_call_fn,
    reason = "public nonzero span ID constructor preserves the checked ID API"
  )]
  #[inline]
  #[must_use]
  pub const fn from_non_zero_u64(id: NonZeroU64) -> Self {
    Self(id)
  }

  /// Returns the span's ID as a `u64`.
  #[must_use]
  pub const fn into_u64(self) -> u64 {
    self.0.get()
  }

  /// Returns the span's ID as a `NonZeroU64`.
  #[inline]
  #[must_use]
  pub const fn into_non_zero_u64(self) -> NonZeroU64 {
    self.0
  }
}

impl<'a> From<&'a Id> for Option<Id> {
  fn from(id: &'a Id) -> Self {
    Some(*id)
  }
}

// ===== impl Attributes =====

impl<'a> Attributes<'a> {
  /// Returns `Attributes` describing a new child span of the current span,
  /// with the provided metadata and values.
  #[allow(
    clippy::single_call_fn,
    reason = "public span Attributes constructor is used by downstream subscriber tests and instrumentation"
  )]
  #[must_use]
  pub const fn new(metadata: &'static Metadata<'static>, values: &'a field::ValueSet<'a>) -> Self {
    Self {
      metadata,
      values,
      parent: Parent::Current,
    }
  }

  /// Returns `Attributes` describing a new span at the root of its own trace
  /// tree, with the provided metadata and values.
  #[must_use]
  pub const fn new_root(metadata: &'static Metadata<'static>, values: &'a field::ValueSet<'a>) -> Self {
    Self {
      metadata,
      values,
      parent: Parent::Root,
    }
  }

  /// Returns `Attributes` describing a new child span of the specified
  /// parent span, with the provided metadata and values.
  #[must_use]
  pub const fn child_of(parent: Id, metadata: &'static Metadata<'static>, values: &'a field::ValueSet<'a>) -> Self {
    Attributes {
      metadata,
      values,
      parent: Parent::Explicit(parent),
    }
  }

  /// Returns a reference to the new span's metadata.
  #[must_use]
  pub const fn metadata(&self) -> &'static Metadata<'static> {
    self.metadata
  }

  /// Returns a reference to a `ValueSet` containing any values the new span
  /// was created with.
  #[must_use]
  pub const fn values(&self) -> &field::ValueSet<'a> {
    self.values
  }

  /// Returns true if the new span should be a root.
  #[must_use]
  pub const fn is_root(&self) -> bool {
    matches!(self.parent, Parent::Root)
  }

  /// Returns true if the new span's parent should be determined based on the
  /// current context.
  ///
  /// If this is true and the current thread is currently inside a span, then
  /// that span should be the new span's parent. Otherwise, if the current
  /// thread is _not_ inside a span, then the new span will be the root of its
  /// own trace tree.
  #[must_use]
  pub const fn is_contextual(&self) -> bool {
    matches!(self.parent, Parent::Current)
  }

  /// Returns the new span's explicitly-specified parent, if there is one.
  ///
  /// Otherwise (if the new span is a root or is a child of the current span),
  /// returns `None`.
  #[must_use]
  pub const fn parent(&self) -> Option<&Id> {
    match self.parent {
      Parent::Explicit(ref parent) => Some(parent),
      Parent::Root | Parent::Current => None,
    }
  }

  /// Records all the fields in this set of `Attributes` with the provided
  /// [Visitor].
  ///
  /// [visitor]: super::field::Visit
  pub fn record(&self, visitor: &mut dyn field::Visit) {
    self.values.record(visitor);
  }

  /// Returns `true` if this set of `Attributes` contains a value for the
  /// given `Field`.
  #[must_use]
  pub fn contains(&self, field: &field::Field) -> bool {
    self.values.contains(field)
  }

  /// Returns true if this set of `Attributes` contains _no_ values.
  #[must_use]
  pub fn is_empty(&self) -> bool {
    self.values.is_empty()
  }

  /// Returns the set of all [fields] defined by this span's [`Metadata`].
  ///
  /// Note that the [`FieldSet`] returned by this method includes *all* the
  /// fields declared by this span, not just those with values that are recorded
  /// as part of this set of `Attributes`. Other fields with values not present in
  /// this `Attributes`' value set may [record] values later.
  ///
  /// [fields]: crate::field
  /// [record]: Attributes::record()
  /// [`Metadata`]: crate::metadata::Metadata
  /// [`FieldSet`]: crate::field::FieldSet
  #[must_use]
  pub const fn fields(&self) -> &FieldSet {
    self.values.field_set()
  }
}

// ===== impl Record =====

impl<'a> Record<'a> {
  /// Constructs a new `Record` from a `ValueSet`.
  #[allow(
    clippy::single_call_fn,
    reason = "public record constructor remains the manual field-recording entry point"
  )]
  #[must_use]
  pub const fn new(values: &'a field::ValueSet<'a>) -> Self {
    Self {
      values,
    }
  }

  /// Records all the fields in this `Record` with the provided [Visitor].
  ///
  /// [visitor]: super::field::Visit
  pub fn record(&self, visitor: &mut dyn field::Visit) {
    self.values.record(visitor);
  }

  /// Returns the number of fields that would be visited from this `Record`
  /// when [`Record::record()`] is called
  ///
  /// [`Record::record()`]: Record::record()
  #[must_use]
  pub fn len(&self) -> usize {
    self.values.len()
  }

  /// Returns `true` if this `Record` contains a value for the given `Field`.
  #[must_use]
  pub fn contains(&self, field: &field::Field) -> bool {
    self.values.contains(field)
  }

  /// Returns true if this `Record` contains _no_ values.
  #[must_use]
  pub fn is_empty(&self) -> bool {
    self.values.is_empty()
  }
}

// ===== impl Current =====

impl Current {
  /// Constructs a new `Current` that indicates the current context is a span
  /// with the given `metadata` and `metadata`.
  #[must_use]
  pub const fn new(id: Id, metadata: &'static Metadata<'static>) -> Self {
    Self {
      inner: CurrentInner::Current {
        id,
        metadata,
      },
    }
  }

  /// Constructs a new `Current` that indicates the current context is *not*
  /// in a span.
  #[must_use]
  pub const fn none() -> Self {
    Self {
      inner: CurrentInner::None
    }
  }

  /// Constructs a new `Current` that indicates the `Subscriber` does not
  /// track a current span.
  #[allow(
    clippy::single_call_fn,
    reason = "name the unknown current-span state separately from a known empty span"
  )]
  pub(crate) const fn unknown() -> Self {
    Self {
      inner: CurrentInner::Unknown,
    }
  }

  /// Returns `true` if the `Subscriber` that constructed this `Current` tracks a
  /// current span.
  ///
  /// If this returns `true` and [`id`], [`metadata`], or [`into_inner`]
  /// return `None`, that indicates that we are currently known to *not* be
  /// inside a span. If this returns `false`, those methods will also return
  /// `None`, but in this case, that is because the subscriber does not keep
  /// track of the currently-entered span.
  ///
  /// [`id`]: Current::id()
  /// [`metadata`]: Current::metadata()
  /// [`into_inner`]: Current::into_inner()
  #[must_use]
  pub const fn is_known(&self) -> bool {
    !matches!(self.inner, CurrentInner::Unknown)
  }

  /// Consumes `self` and returns the span `Id` and `Metadata` of the current
  /// span, if one exists and is known.
  #[must_use]
  pub const fn into_inner(self) -> Option<(Id, &'static Metadata<'static>)> {
    match self.inner {
      CurrentInner::Current {
        id,
        metadata,
      } => Some((id, metadata)),
      CurrentInner::None | CurrentInner::Unknown => None,
    }
  }

  /// Borrows the `Id` of the current span, if one exists and is known.
  #[must_use]
  pub const fn id(&self) -> Option<&Id> {
    match self.inner {
      CurrentInner::Current {
        ref id, ..
      } => Some(id),
      CurrentInner::None | CurrentInner::Unknown => None,
    }
  }

  /// Borrows the `Metadata` of the current span, if one exists and is known.
  #[must_use]
  pub const fn metadata(&self) -> Option<&'static Metadata<'static>> {
    match self.inner {
      CurrentInner::Current {
        metadata, ..
      } => Some(metadata),
      CurrentInner::None | CurrentInner::Unknown => None,
    }
  }
}

impl<'a> From<&'a Current> for Option<&'a Id> {
  fn from(cur: &'a Current) -> Self {
    cur.id()
  }
}

impl<'a> From<&'a Current> for Option<Id> {
  fn from(cur: &'a Current) -> Self {
    cur.id().copied()
  }
}

impl From<Current> for Option<Id> {
  fn from(cur: Current) -> Self {
    match cur.inner {
      CurrentInner::Current {
        id, ..
      } => Some(id),
      CurrentInner::None | CurrentInner::Unknown => None,
    }
  }
}

impl<'a> From<&'a Current> for Option<&'static Metadata<'static>> {
  fn from(cur: &'a Current) -> Self {
    cur.metadata()
  }
}

#[cfg(test)]
mod tests {
  use core::fmt;
  use core::num::NonZeroU64;

  use strict_test_support::TestFailure;
  use strict_test_support::ensure;
  use strict_test_support::ensure_eq;
  use strict_test_support::ensure_some;

  use super::*;
  use crate::callsite::Callsite;
  use crate::field::Field;
  use crate::field::Value;
  use crate::field::Visit;
  use crate::metadata::Kind;
  use crate::metadata::Level;
  use crate::subscriber::Interest;

  /// Bit marking that `alpha` was recorded.
  const SAW_ALPHA: u8 = 0b001;
  /// Bit marking that `beta` was recorded.
  const SAW_BETA: u8 = 0b010;
  /// Bit marking that an undeclared field was recorded.
  const SAW_OTHER: u8 = 0b100;

  /// Non-zero callsite fixture so callsite identity is pointer-distinct.
  struct SpanTestCallsite {
    /// Makes this fixture non-zero sized.
    _non_zero: u8,
  }

  /// Callsite fixture backing the span data-model tests.
  static SPAN_TEST_CALLSITE: SpanTestCallsite = SpanTestCallsite {
    _non_zero: 1
  };

  /// Metadata fixture with populated fields.
  static SPAN_TEST_META: Metadata<'static> = metadata! {
      name: "core_span",
      target: module_path!(),
      level: Level::INFO,
      fields: &["alpha", "beta"],
      callsite: &SPAN_TEST_CALLSITE,
      kind: Kind::SPAN,
  };

  impl Callsite for SpanTestCallsite {
    fn set_interest(&self, _interest: Interest) {}

    fn metadata(&self) -> &Metadata<'_> {
      &SPAN_TEST_META
    }
  }

  /// Visitor that remembers which field names were recorded.
  #[derive(Debug, Default)]
  struct FieldNameVisitor {
    /// Bitset of field names recorded by the visitor.
    seen: u8,
  }

  impl Visit for FieldNameVisitor {
    fn record_debug(&mut self, field: &Field, _value: &dyn fmt::Debug) {
      self.seen |= match field.name() {
        "alpha" => SAW_ALPHA,
        "beta" => SAW_BETA,
        _other => SAW_OTHER,
      };
    }
  }

  #[test]
  fn span_id_round_trips_through_checked_and_nonzero_constructors() -> Result<(), TestFailure> {
    let id = Id::from_non_zero_u64(NonZeroU64::MIN);

    ensure(Id::try_from_u64(0).is_none(), "zero is rejected as a span id")?;
    ensure_eq(&id.into_u64(), &1_u64, "nonzero id converts to raw u64")?;
    ensure_eq(&id.into_non_zero_u64(), &NonZeroU64::MIN, "nonzero id converts back to NonZeroU64")?;

    let from_raw = ensure_some(Id::try_from_u64(1), "one is accepted as a span id")?;
    let from_ref: Option<Id> = Option::from(&from_raw);

    ensure(from_raw == id, "checked and nonzero constructors agree")?;
    ensure(from_ref == Some(id), "span id converts from reference to copied option")
  }

  #[test]
  fn attributes_report_contextual_root_and_explicit_parent_contracts() -> Result<(), TestFailure> {
    let fields = SPAN_TEST_META.fields();
    let alpha = ensure_some(fields.field("alpha"), "alpha field exists")?;
    let beta = ensure_some(fields.field("beta"), "beta field exists")?;
    let value: &dyn Value = &"alpha value";
    let values = [(&alpha, Some(value)), (&beta, None)];
    let value_set = fields.value_set(&values);

    let contextual = Attributes::new(&SPAN_TEST_META, &value_set);
    ensure(contextual.is_contextual(), "new attributes use contextual parenting")?;
    ensure(!contextual.is_root(), "contextual attributes are not explicit roots")?;
    ensure(contextual.parent().is_none(), "contextual attributes have no explicit parent")?;
    ensure(contextual.metadata().name() == "core_span", "attributes expose metadata")?;
    ensure(contextual.values().contains(&alpha), "attributes expose recorded values")?;
    ensure(contextual.contains(&alpha), "attributes contain present fields")?;
    ensure(!contextual.contains(&beta), "attributes do not contain empty fields")?;
    ensure(
      contextual.fields().contains(&beta),
      "attributes field set includes empty declared fields",
    )?;
    ensure(!contextual.is_empty(), "attributes with a present value are not empty")?;

    let root = Attributes::new_root(&SPAN_TEST_META, &value_set);
    ensure(root.is_root(), "root attributes report explicit root parenting")?;
    ensure(!root.is_contextual(), "root attributes are not contextual")?;
    ensure(root.parent().is_none(), "root attributes have no explicit parent")?;

    let parent_id = Id::from_non_zero_u64(NonZeroU64::MIN);
    let child = Attributes::child_of(parent_id, &SPAN_TEST_META, &value_set);
    let explicit_parent = ensure_some(child.parent(), "child attributes expose an explicit parent")?;

    ensure(!child.is_root(), "child attributes are not roots")?;
    ensure(!child.is_contextual(), "child attributes are not contextual")?;
    ensure(*explicit_parent == parent_id, "child attributes preserve the explicit parent id")
  }

  #[test]
  fn attributes_and_records_forward_present_values_to_visitors() -> Result<(), TestFailure> {
    let fields = SPAN_TEST_META.fields();
    let alpha = ensure_some(fields.field("alpha"), "alpha field exists")?;
    let beta = ensure_some(fields.field("beta"), "beta field exists")?;
    let first: &dyn Value = &"alpha value";
    let second: &dyn Value = &"beta value";
    let values = [(&alpha, Some(first)), (&beta, Some(second))];
    let value_set = fields.value_set(&values);

    let attributes = Attributes::new_root(&SPAN_TEST_META, &value_set);
    ensure(attributes.is_root(), "recorded attributes can be explicit roots")?;
    let mut attributes_visitor = FieldNameVisitor::default();
    attributes.record(&mut attributes_visitor);

    ensure(attributes_visitor.seen & SAW_ALPHA != 0, "attributes record alpha")?;
    ensure(attributes_visitor.seen & SAW_BETA != 0, "attributes record beta")?;
    ensure(attributes_visitor.seen & SAW_OTHER == 0, "attributes record no undeclared fields")?;

    let parent_id = Id::from_non_zero_u64(NonZeroU64::MIN);
    let child_attributes = Attributes::child_of(parent_id, &SPAN_TEST_META, &value_set);
    let child_parent = ensure_some(child_attributes.parent(), "recorded child attributes expose parent")?;
    ensure(*child_parent == parent_id, "recorded child attributes preserve parent")?;

    let record = Record::new(&value_set);
    let mut record_visitor = FieldNameVisitor::default();
    record.record(&mut record_visitor);

    ensure_eq(&record.len(), &2_usize, "record reports present value count")?;
    ensure(record.contains(&alpha), "record contains alpha")?;
    ensure(record.contains(&beta), "record contains beta")?;
    ensure(!record.is_empty(), "record with present values is not empty")?;
    ensure(record_visitor.seen & SAW_ALPHA != 0, "record forwards alpha")?;
    ensure(record_visitor.seen & SAW_BETA != 0, "record forwards beta")?;
    ensure(record_visitor.seen & SAW_OTHER == 0, "record forwards no undeclared fields")?;

    let empty_value_set = fields.value_set(&[]);
    let empty_record = Record::new(&empty_value_set);
    ensure_eq(&empty_record.len(), &0_usize, "empty record has no values")?;
    ensure(empty_record.is_empty(), "empty record reports empty")?;
    ensure(!empty_record.contains(&alpha), "empty record contains no fields")
  }

  #[test]
  fn current_span_states_distinguish_known_none_and_unknown() -> Result<(), TestFailure> {
    let id = Id::from_non_zero_u64(NonZeroU64::MIN);
    let current = Current::new(id, &SPAN_TEST_META);

    ensure(current.is_known(), "current span state is known")?;
    ensure(current.id().is_some_and(|current_id| *current_id == id), "current exposes id")?;
    ensure(
      current.metadata().is_some_and(|metadata| metadata.name() == "core_span"),
      "current exposes metadata",
    )?;

    let by_ref: Option<&Id> = Option::from(&current);
    let by_ref_owned: Option<Id> = Option::from(&current);
    let by_ref_metadata: Option<&'static Metadata<'static>> = Option::from(&current);
    let owned_current_id: Option<Id> = Option::from(Current::new(id, &SPAN_TEST_META));
    ensure(by_ref.is_some(), "current converts by reference to id")?;
    ensure(by_ref_owned == Some(id), "current converts by reference to copied id")?;
    ensure(owned_current_id == Some(id), "current converts by value to copied id")?;
    ensure(
      by_ref_metadata.is_some_and(|metadata| metadata.name() == "core_span"),
      "current converts by reference to metadata",
    )?;

    let inner = ensure_some(current.into_inner(), "current consumes into id and metadata")?;
    ensure(inner.0 == id, "current inner id is preserved")?;
    ensure(inner.1.name() == "core_span", "current inner metadata is preserved")?;

    let none = Current::none();
    ensure(none.is_known(), "known-none current state is known")?;
    ensure(none.id().is_none(), "known-none current has no id")?;
    ensure(none.metadata().is_none(), "known-none current has no metadata")?;
    let none_id: Option<Id> = Option::from(none);
    ensure(none_id.is_none(), "known-none current converts to no id")?;
    let another_none = Current::none();
    ensure(another_none.into_inner().is_none(), "known-none current consumes to no inner span")?;

    let unknown = Current::unknown();
    ensure(!unknown.is_known(), "unknown current state is not known")?;
    ensure(unknown.id().is_none(), "unknown current has no id")?;
    ensure(unknown.metadata().is_none(), "unknown current has no metadata")?;
    let unknown_id: Option<Id> = Option::from(unknown);
    ensure(unknown_id.is_none(), "unknown current converts to no id")
  }
}
