[package]
name = "tracing-tower"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition.workspace = true
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Compatibility with the `tower` ecosystem.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[features]
default = ["tower-layer", "tower-make"]
tower-layer = ["dep:tower-layer"]
tower-make = ["dep:tower_make", "dep:pin-project-lite"]
http = ["dep:http"]

[dependencies]
tracing = { workspace = true, features = ["std"] }
futures = { workspace = true, default-features = true }
tower-service = { workspace = true }
tower-layer = { workspace = true, optional = true }
tower_make = { workspace = true, optional = true }
pin-project-lite = { workspace = true, optional = true }
http = { workspace = true, optional = true }

[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
