#![deny(warnings)]
#![doc = "Macro expansion integration coverage."]
#![no_implicit_prelude]

#[cfg(test)]
mod tests {
    // We call all macros in this module with `no_implicit_prelude` to ensure they do not depend on the standard prelude.
    extern crate strict_test_support;
    extern crate tracing as tracing_crate;
    #[cfg(target_arch = "wasm32")]
    extern crate wasm_bindgen_test;

    use ::core::{option::Option, result::Result};
    use ::std::{
        convert::From as _,
        fmt::{self, Display, Formatter},
        string::String,
        write,
    };
    use strict_test_support::{TestFailure, ensure};
    use tracing_crate::metadata::Kind;
    use tracing_crate::{
        Level, callsite, debug, debug_span, enabled, error, error_span, event, event_enabled,
        field, info, info_span, record_all, span, span_enabled, trace, trace_span, warn, warn_span,
    };

    /// A type that implements `Display` and `Debug`, but not `Value`.
    #[derive(Debug)]
    struct DisplayDebug;

    impl Display for DisplayDebug {
        fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
            write!(f, "Foo")
        }
    }

    fn temporary_string() -> String {
        String::from("temporary value")
    }

    fn temporary_str_ref() -> &'static str {
        "temporary value"
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn temporary_field_expressions_live_for_macro_dispatch() -> Result<(), TestFailure> {
        event!(
            Level::INFO,
            plain = temporary_string(),
            debug_ref = ?temporary_str_ref(),
            display_temp = %temporary_string(),
            "{}",
            temporary_str_ref()
        );

        span!(
            Level::INFO,
            "temporary_span",
            plain = temporary_string(),
            debug_ref = ?temporary_str_ref(),
            display_temp = %temporary_string()
        );

        let span = info_span!(
            "recorded",
            plain = field::Empty,
            debug_ref = field::Empty,
            display_temp = field::Empty
        );
        record_all!(
            span,
            plain = temporary_string(),
            debug_ref = ?temporary_str_ref(),
            display_temp = %temporary_string()
        );

        let retained = String::from("retained");
        event!(Level::INFO, retained = retained, ?retained);
        let still_available = &retained;
        ensure(
            still_available == "retained",
            "retained field value should remain available after event",
        )
    }

    // Tests that macros work across various invocation syntax.
    //
    // These are quite repetitive, and _could_ be generated by a macro. However,
    // they're compile-time tests, so I want to get line numbers etc out of
    // failures, and producing them with a macro would muddy the waters a bit.

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn span() {
        span!(target: "foo_events", Level::DEBUG, "foo", bar.baz = ?2, quux = %3, quuux = 4);
        span!(target: "foo_events", Level::DEBUG, "foo", bar.baz = 2, quux = 3);
        span!(target: "foo_events", Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
        span!(target: "foo_events", Level::DEBUG, "foo");
        span!(target: "foo_events", Level::DEBUG, "bar",);
        span!(Level::DEBUG, "foo", bar.baz = 2, quux = 3);
        span!(Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
        span!(Level::DEBUG, "foo", bar.baz = 2, quux = 3);
        span!(Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
        span!(Level::DEBUG, "foo", bar.baz = ?2);
        span!(Level::DEBUG, "foo", bar.baz = %2);
        span!(Level::DEBUG, "foo");
        span!(Level::DEBUG, "bar",);
        span!(
            Level::DEBUG,
            "bar",
            foo = display("foo"),
            quux = debug(Option::Some(2))
        );
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn trace_span() {
        trace_span!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
        trace_span!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
        trace_span!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
        trace_span!(target: "foo_events", "foo");
        trace_span!(target: "foo_events", "bar",);
        trace_span!("foo", bar.baz = 2, quux = 3);
        trace_span!("foo", bar.baz = 2, quux = 4,);
        trace_span!("foo", bar.baz = ?2);
        trace_span!("foo", bar.baz = %2);
        trace_span!("bar");
        trace_span!("bar",);
        trace_span!("bar", foo = display("foo"), quux = debug(Option::Some(2)));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn debug_span() {
        debug_span!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
        debug_span!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
        debug_span!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
        debug_span!(target: "foo_events", "foo");
        debug_span!(target: "foo_events", "bar",);
        debug_span!("foo", bar.baz = 2, quux = 3);
        debug_span!("foo", bar.baz = 2, quux = 4,);
        debug_span!("foo", bar.baz = ?2);
        debug_span!("foo", bar.baz = %2);
        debug_span!("bar");
        debug_span!("bar",);
        debug_span!("bar", foo = display("foo"), quux = debug(Option::Some(2)));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn info_span() {
        info_span!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
        info_span!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
        info_span!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
        info_span!(target: "foo_events", "foo");
        info_span!(target: "foo_events", "bar",);
        info_span!("foo", bar.baz = 2, quux = 3);
        info_span!("foo", bar.baz = 2, quux = 4,);
        info_span!("foo", bar.baz = ?2);
        info_span!("foo", bar.baz = %2);
        info_span!("bar");
        info_span!("bar",);
        info_span!("bar", foo = display("foo"), quux = debug(Option::Some(2)));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn warn_span() {
        warn_span!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
        warn_span!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
        warn_span!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
        warn_span!(target: "foo_events", "foo");
        warn_span!(target: "foo_events", "bar",);
        warn_span!("foo", bar.baz = 2, quux = 3);
        warn_span!("foo", bar.baz = 2, quux = 4,);
        warn_span!("foo", bar.baz = ?2);
        warn_span!("foo", bar.baz = %2);
        warn_span!("bar");
        warn_span!("bar",);
        warn_span!("bar", foo = display("foo"), quux = debug(Option::Some(2)));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn error_span() {
        error_span!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
        error_span!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
        error_span!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
        error_span!(target: "foo_events", "foo");
        error_span!(target: "foo_events", "bar",);
        error_span!("foo", bar.baz = 2, quux = 3);
        error_span!("foo", bar.baz = 2, quux = 4,);
        error_span!("foo", bar.baz = ?2);
        error_span!("foo", bar.baz = %2);
        error_span!("bar");
        error_span!("bar",);
        error_span!("bar", foo = display("foo"), quux = debug(Option::Some(2)));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn span_root() {
        span!(target: "foo_events", parent: Option::None, Level::TRACE, "foo", bar.baz = 2, quux = 3);
        span!(target: "foo_events", parent: Option::None, Level::TRACE, "foo", bar.baz = 2, quux = 3);
        span!(target: "foo_events", parent: Option::None, Level::TRACE, "foo", bar.baz = 2, quux = 4,);
        span!(target: "foo_events", parent: Option::None, Level::TRACE, "foo");
        span!(target: "foo_events", parent: Option::None, Level::TRACE, "bar",);
        span!(
            parent: Option::None,
            Level::DEBUG,
            "foo",
            bar.baz = 2,
            quux = 3
        );
        span!(
            parent: Option::None,
            Level::DEBUG,
            "foo",
            bar.baz = 2,
            quux = 4,
        );
        span!(parent: Option::None, Level::DEBUG, "foo");
        span!(parent: Option::None, Level::DEBUG, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn trace_span_root() {
        trace_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 3);
        trace_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 4,);
        trace_span!(target: "foo_events", parent: Option::None, "foo");
        trace_span!(target: "foo_events", parent: Option::None, "bar",);
        trace_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 3
        );
        trace_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 4,
        );
        trace_span!(parent: Option::None, "foo");
        trace_span!(parent: Option::None, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn debug_span_root() {
        debug_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 3);
        debug_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 4,);
        debug_span!(target: "foo_events", parent: Option::None, "foo");
        debug_span!(target: "foo_events", parent: Option::None, "bar",);
        debug_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 3
        );
        debug_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 4,
        );
        debug_span!(parent: Option::None, "foo");
        debug_span!(parent: Option::None, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn info_span_root() {
        info_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 3);
        info_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 4,);
        info_span!(target: "foo_events", parent: Option::None, "foo");
        info_span!(target: "foo_events", parent: Option::None, "bar",);
        info_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 3
        );
        info_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 4,
        );
        info_span!(parent: Option::None, "foo");
        info_span!(parent: Option::None, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn warn_span_root() {
        warn_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 3);
        warn_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 4,);
        warn_span!(target: "foo_events", parent: Option::None, "foo");
        warn_span!(target: "foo_events", parent: Option::None, "bar",);
        warn_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 3
        );
        warn_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 4,
        );
        warn_span!(parent: Option::None, "foo");
        warn_span!(parent: Option::None, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn error_span_root() {
        error_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 3);
        error_span!(target: "foo_events", parent: Option::None, "foo", bar.baz = 2, quux = 4,);
        error_span!(target: "foo_events", parent: Option::None, "foo");
        error_span!(target: "foo_events", parent: Option::None, "bar",);
        error_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 3
        );
        error_span!(
            parent: Option::None,
            "foo",
            bar.baz = 2,
            quux = 4,
        );
        error_span!(parent: Option::None, "foo");
        error_span!(parent: Option::None, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn span_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        span!(target: "foo_events", parent: &parent_span, Level::TRACE, "foo", bar.baz = 2, quux = 3);
        span!(target: "foo_events", parent: &parent_span, Level::TRACE, "foo", bar.baz = 2, quux = 4,);
        span!(target: "foo_events", parent: &parent_span, Level::TRACE, "foo");
        span!(target: "foo_events", parent: &parent_span, Level::TRACE, "bar",);
        span!(parent: &parent_span, Level::DEBUG, "foo", bar.baz = 2, quux = 3);
        span!(parent: &parent_span, Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
        span!(parent: &parent_span, Level::DEBUG, "foo");
        span!(parent: &parent_span, Level::DEBUG, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn trace_span_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        trace_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        trace_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 4,);
        trace_span!(target: "foo_events", parent: &parent_span, "foo");
        trace_span!(target: "foo_events", parent: &parent_span, "bar",);

        trace_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        trace_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 4,);

        trace_span!(parent: &parent_span, "foo");
        trace_span!(parent: &parent_span, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn debug_span_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        debug_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        debug_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 4,);
        debug_span!(target: "foo_events", parent: &parent_span, "foo");
        debug_span!(target: "foo_events", parent: &parent_span, "bar",);

        debug_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        debug_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 4,);

        debug_span!(parent: &parent_span, "foo");
        debug_span!(parent: &parent_span, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn info_span_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        info_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        info_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 4,);
        info_span!(target: "foo_events", parent: &parent_span, "foo");
        info_span!(target: "foo_events", parent: &parent_span, "bar",);

        info_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        info_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 4,);

        info_span!(parent: &parent_span, "foo");
        info_span!(parent: &parent_span, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn warn_span_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        warn_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        warn_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 4,);
        warn_span!(target: "foo_events", parent: &parent_span, "foo");
        warn_span!(target: "foo_events", parent: &parent_span, "bar",);

        warn_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        warn_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 4,);

        warn_span!(parent: &parent_span, "foo");
        warn_span!(parent: &parent_span, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn error_span_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        error_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        error_span!(target: "foo_events", parent: &parent_span, "foo", bar.baz = 2, quux = 4,);
        error_span!(target: "foo_events", parent: &parent_span, "foo");
        error_span!(target: "foo_events", parent: &parent_span, "bar",);

        error_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 3);
        error_span!(parent: &parent_span, "foo", bar.baz = 2, quux = 4,);

        error_span!(parent: &parent_span, "foo");
        error_span!(parent: &parent_span, "bar",);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn span_with_non_rust_symbol() {
        span!(Level::TRACE, "non-rust", "guid:x-request-id" = ?"abcdef", "more {}", 42);
        span!(Level::TRACE, "non-rust", "guid:x-request-id" = %"abcdef", "more {}", 51);
        span!(
            Level::TRACE,
            "non-rust",
            "guid:x-request-id" = "abcdef",
            "more {}",
            60
        );
        span!(Level::TRACE, "non-rust", "guid:x-request-id" = ?"abcdef");
        span!(Level::TRACE, "non-rust", "guid:x-request-id" = %"abcdef");
        span!(Level::TRACE, "non-rust", "guid:x-request-id" = "abcdef");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn large_span() {
        span!(
            Level::TRACE,
            "spans with more than 32 fields have been supported since #2508",
            a = 1,
            b = 2,
            c = 3,
            d = 4,
            e = 5,
            f = 6,
            g = 7,
            h = 8,
            i = 9,
            j = 10,
            k = 11,
            l = 12,
            m = 13,
            n = 14,
            o = 15,
            p = 16,
            q = 17,
            r = 18,
            s = 19,
            t = 20,
            u = 21,
            v = 22,
            w = 23,
            x = 24,
            y = 25,
            z = 26,
            aa = 27,
            bb = 28,
            cc = 29,
            dd = 30,
            ee = 31,
            ff = 32,
            gg = 33
        );
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn event() {
        event!(Level::DEBUG, foo = ?3, bar.baz = %2, quux = false);
        event!(Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
        event!(Level::DEBUG, foo = 3, bar.baz = 3,);
        event!(Level::DEBUG, "foo");
        event!(Level::DEBUG, "foo: {}", 3);
        event!(Level::INFO, foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
        event!(
            Level::INFO,
            foo = 3,
            bar.baz = 2,
            quux = false,
            "hello world {:?}",
            42
        );
        event!(Level::INFO, foo = 3, bar.baz = 3, "hello world {:?}", 42,);
        event!(Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(Level::DEBUG, { foo = ?2, bar.baz = %78 }, "quux");
        event!(target: "foo_events", Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
        event!(target: "foo_events", Level::DEBUG, foo = 3, bar.baz = 3,);
        event!(target: "foo_events", Level::DEBUG, "foo");
        event!(target: "foo_events", Level::DEBUG, "foo: {}", 3);
        event!(target: "foo_events", Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(target: "foo_events", Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(target: "foo_events", Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(target: "foo_events", Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
        let foo = 1;
        event!(Level::DEBUG, ?foo);
        event!(Level::DEBUG, %foo);
        event!(Level::DEBUG, foo);
        event!(
            Level::DEBUG,
            foo = display("foo"),
            quux = debug(Option::Some(2))
        );
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn enabled() {
        enabled!(Level::DEBUG, foo, bar.baz, quux,);
        enabled!(Level::DEBUG, message);
        enabled!(Level::INFO, foo, bar.baz, quux, message,);
        enabled!(Level::INFO, foo, bar., message,);
        enabled!(Level::DEBUG, foo);

        enabled!(Level::DEBUG);
        enabled!(target: "rando", Level::DEBUG);
        enabled!(target: "rando", Level::DEBUG, field);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn span_enabled() {
        span_enabled!(Level::DEBUG, foo, bar.baz, quux,);
        span_enabled!(Level::DEBUG, message);
        span_enabled!(Level::INFO, foo, bar.baz, quux, message,);
        span_enabled!(Level::INFO, foo, bar., message,);
        span_enabled!(Level::DEBUG, foo);

        span_enabled!(Level::DEBUG);
        span_enabled!(target: "rando", Level::DEBUG);
        span_enabled!(target: "rando", Level::DEBUG, field);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn event_enabled() {
        event_enabled!(Level::DEBUG, foo, bar.baz, quux,);
        event_enabled!(Level::DEBUG, message);
        event_enabled!(Level::INFO, foo, bar.baz, quux, message,);
        event_enabled!(Level::INFO, foo, bar., message,);
        event_enabled!(Level::DEBUG, foo);

        event_enabled!(Level::DEBUG);
        event_enabled!(target: "rando", Level::DEBUG);
        event_enabled!(target: "rando", Level::DEBUG, field);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn locals_with_message() {
        let data = (42, "forty-two");
        let private_data = "private";
        let error = "a bad error";
        event!(Level::ERROR, %error, "Received error");
        event!(
            target: "app_events",
            Level::WARN,
            private_data,
            ?data,
            "App warning: {}",
            error
        );
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn locals_no_message() {
        let data = (42, "forty-two");
        let private_data = "private";
        let error = "a bad error";
        event!(
            name: "foo",
            target: "app_events",
            Level::WARN,
            private_data,
            ?data,
        );
        event!(
            name: "foo",
            parent: Option::None,
            Level::WARN,
            private_data,
            ?data,
        );
        event!(
            target: "app_events",
            Level::WARN,
            private_data,
            ?data,
        );
        event!(
            target: "app_events",
            Level::WARN,
            private_data,
            ?data,
            error,
        );
        event!(
            target: "app_events",
            Level::WARN,
            private_data,
            ?data,
            error
        );
        event!(Level::WARN, private_data, ?data, error,);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn trace() {
        trace!(foo = ?3, bar.baz = %2, quux = false);
        trace!(foo = 3, bar.baz = 2, quux = false);
        trace!(foo = 3, bar.baz = 3,);
        trace!("foo" = 3, bar.baz = 3,);
        trace!(foo = 3, "bar.baz" = 3,);
        trace!("foo");
        trace!("foo: {}", 3);
        trace!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
        trace!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
        trace!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
        trace!({ foo = 3, bar.baz = 80 }, "quux");
        trace!({ "foo" = 3, "bar.baz" = 80 }, "quux");
        trace!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!({ foo = 2, bar.baz = 78 }, "quux");
        trace!({ foo = ?2, bar.baz = %78 }, "quux");
        trace!(name: "foo", foo = 3, bar.baz = 2, quux = false);
        trace!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        trace!(name: "foo", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        trace!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        trace!(target: "foo_events", foo = 3, bar.baz = 3,);
        trace!(target: "foo_events", "foo");
        trace!(target: "foo_events", "foo: {}", 3);
        trace!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
        trace!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
        let foo = 1;
        trace!(?foo);
        trace!(%foo);
        trace!(foo);
        trace!("foo" = ?foo);
        trace!("foo" = %foo);
        trace!("foo" = foo);
        trace!(name: "foo", ?foo);
        trace!(name: "foo", %foo);
        trace!(name: "foo", foo);
        trace!(name: "foo", ?foo, true, "message");
        trace!(name: "foo", %foo, true, "message");
        trace!(name: "foo", foo, true, "message");
        trace!(target: "foo_events", ?foo);
        trace!(target: "foo_events", %foo);
        trace!(target: "foo_events", foo);
        trace!(target: "foo_events", ?foo, true, "message");
        trace!(target: "foo_events", %foo, true, "message");
        trace!(target: "foo_events", foo, true, "message");
        trace!(name: "foo", target: "foo_events", ?foo);
        trace!(name: "foo", target: "foo_events", %foo);
        trace!(name: "foo", target: "foo_events", foo);
        let display_debug = DisplayDebug;
        trace!(?display_debug);
        trace!(%display_debug);
        trace!(name: "foo", ?display_debug);
        trace!(name: "foo", %display_debug);
        trace!(name: "foo", ?display_debug, true, "message");
        trace!(name: "foo", %display_debug, true, "message");
        trace!(target: "foo_events", ?display_debug);
        trace!(target: "foo_events", %display_debug);
        trace!(target: "foo_events", ?display_debug, true, "message");
        trace!(target: "foo_events", %foo, true, "message");
        trace!(name: "foo", target: "foo_events", ?foo, true, "message");
        trace!(name: "foo", target: "foo_events", %foo, true, "message");
        trace!(foo = display("foo"), quux = debug(foo));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn debug() {
        debug!(foo = ?3, bar.baz = %2, quux = false);
        debug!(foo = 3, bar.baz = 2, quux = false);
        debug!(foo = 3, bar.baz = 3,);
        debug!("foo" = 3, bar.baz = 3,);
        debug!(foo = 3, "bar.baz" = 3,);
        debug!("foo");
        debug!("foo: {}", 3);
        debug!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
        debug!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
        debug!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
        debug!({ foo = 3, bar.baz = 80 }, "quux");
        debug!({ "foo" = 3, "bar.baz" = 80 }, "quux");
        debug!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!({ foo = 2, bar.baz = 78 }, "quux");
        debug!({ foo = ?2, bar.baz = %78 }, "quux");
        debug!(name: "foo", foo = 3, bar.baz = 2, quux = false);
        debug!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        debug!(name: "foo", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        debug!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        debug!(target: "foo_events", foo = 3, bar.baz = 3,);
        debug!(target: "foo_events", "foo");
        debug!(target: "foo_events", "foo: {}", 3);
        debug!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
        debug!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
        let foo = 1;
        debug!(?foo);
        debug!(%foo);
        debug!(foo);
        debug!("foo" = ?foo);
        debug!("foo" = %foo);
        debug!("foo" = foo);
        debug!(name: "foo", ?foo);
        debug!(name: "foo", %foo);
        debug!(name: "foo", foo);
        debug!(name: "foo", ?foo, true, "message");
        debug!(name: "foo", %foo, true, "message");
        debug!(name: "foo", foo, true, "message");
        debug!(target: "foo_events", ?foo);
        debug!(target: "foo_events", %foo);
        debug!(target: "foo_events", foo);
        debug!(target: "foo_events", ?foo, true, "message");
        debug!(target: "foo_events", %foo, true, "message");
        debug!(target: "foo_events", foo, true, "message");
        debug!(name: "foo", target: "foo_events", ?foo);
        debug!(name: "foo", target: "foo_events", %foo);
        debug!(name: "foo", target: "foo_events", foo);
        let display_debug = DisplayDebug;
        debug!(?display_debug);
        debug!(%display_debug);
        debug!(name: "foo", ?display_debug);
        debug!(name: "foo", %display_debug);
        debug!(name: "foo", ?display_debug, true, "message");
        debug!(name: "foo", %display_debug, true, "message");
        debug!(target: "foo_events", ?display_debug);
        debug!(target: "foo_events", %display_debug);
        debug!(target: "foo_events", ?display_debug, true, "message");
        debug!(target: "foo_events", %foo, true, "message");
        debug!(name: "foo", target: "foo_events", ?foo, true, "message");
        debug!(name: "foo", target: "foo_events", %foo, true, "message");
        debug!(foo = display("foo"), quux = debug(foo));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn info() {
        info!(foo = ?3, bar.baz = %2, quux = false);
        info!(foo = 3, bar.baz = 2, quux = false);
        info!(foo = 3, bar.baz = 3,);
        info!("foo" = 3, bar.baz = 3,);
        info!(foo = 3, "bar.baz" = 3,);
        info!("foo");
        info!("foo: {}", 3);
        info!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
        info!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
        info!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
        info!({ foo = 3, bar.baz = 80 }, "quux");
        info!({ "foo" = 3, "bar.baz" = 80 }, "quux");
        info!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!({ foo = 2, bar.baz = 78 }, "quux");
        info!({ foo = ?2, bar.baz = %78 }, "quux");
        info!(name: "foo", foo = 3, bar.baz = 2, quux = false);
        info!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        info!(name: "foo", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        info!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        info!(target: "foo_events", foo = 3, bar.baz = 3,);
        info!(target: "foo_events", "foo");
        info!(target: "foo_events", "foo: {}", 3);
        info!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
        info!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
        let foo = 1;
        info!(?foo);
        info!(%foo);
        info!(foo);
        info!("foo" = ?foo);
        info!("foo" = %foo);
        info!("foo" = foo);
        info!(name: "foo", ?foo);
        info!(name: "foo", %foo);
        info!(name: "foo", foo);
        info!(name: "foo", ?foo, true, "message");
        info!(name: "foo", %foo, true, "message");
        info!(name: "foo", foo, true, "message");
        info!(target: "foo_events", ?foo);
        info!(target: "foo_events", %foo);
        info!(target: "foo_events", foo);
        info!(target: "foo_events", ?foo, true, "message");
        info!(target: "foo_events", %foo, true, "message");
        info!(target: "foo_events", foo, true, "message");
        info!(name: "foo", target: "foo_events", ?foo);
        info!(name: "foo", target: "foo_events", %foo);
        info!(name: "foo", target: "foo_events", foo);
        let display_debug = DisplayDebug;
        info!(?display_debug);
        info!(%display_debug);
        info!(name: "foo", ?display_debug);
        info!(name: "foo", %display_debug);
        info!(name: "foo", ?display_debug, true, "message");
        info!(name: "foo", %display_debug, true, "message");
        info!(target: "foo_events", ?display_debug);
        info!(target: "foo_events", %display_debug);
        info!(target: "foo_events", ?display_debug, true, "message");
        info!(target: "foo_events", %foo, true, "message");
        info!(name: "foo", target: "foo_events", ?foo, true, "message");
        info!(name: "foo", target: "foo_events", %foo, true, "message");
        info!(foo = display("foo"), quux = debug(foo));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn warn() {
        warn!(foo = ?3, bar.baz = %2, quux = false);
        warn!(foo = 3, bar.baz = 2, quux = false);
        warn!(foo = 3, bar.baz = 3,);
        warn!("foo" = 3, bar.baz = 3,);
        warn!(foo = 3, "bar.baz" = 3,);
        warn!("foo");
        warn!("foo: {}", 3);
        warn!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
        warn!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
        warn!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
        warn!({ foo = 3, bar.baz = 80 }, "quux");
        warn!({ "foo" = 3, "bar.baz" = 80 }, "quux");
        warn!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!({ foo = 2, bar.baz = 78 }, "quux");
        warn!({ foo = ?2, bar.baz = %78 }, "quux");
        warn!(name: "foo", foo = 3, bar.baz = 2, quux = false);
        warn!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        warn!(name: "foo", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        warn!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        warn!(target: "foo_events", foo = 3, bar.baz = 3,);
        warn!(target: "foo_events", "foo");
        warn!(target: "foo_events", "foo: {}", 3);
        warn!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
        warn!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
        let foo = 1;
        warn!(?foo);
        warn!(%foo);
        warn!(foo);
        warn!("foo" = ?foo);
        warn!("foo" = %foo);
        warn!("foo" = foo);
        warn!(name: "foo", ?foo);
        warn!(name: "foo", %foo);
        warn!(name: "foo", foo);
        warn!(name: "foo", ?foo, true, "message");
        warn!(name: "foo", %foo, true, "message");
        warn!(name: "foo", foo, true, "message");
        warn!(target: "foo_events", ?foo);
        warn!(target: "foo_events", %foo);
        warn!(target: "foo_events", foo);
        warn!(target: "foo_events", ?foo, true, "message");
        warn!(target: "foo_events", %foo, true, "message");
        warn!(target: "foo_events", foo, true, "message");
        warn!(name: "foo", target: "foo_events", ?foo);
        warn!(name: "foo", target: "foo_events", %foo);
        warn!(name: "foo", target: "foo_events", foo);
        let display_debug = DisplayDebug;
        warn!(?display_debug);
        warn!(%display_debug);
        warn!(name: "foo", ?display_debug);
        warn!(name: "foo", %display_debug);
        warn!(name: "foo", ?display_debug, true, "message");
        warn!(name: "foo", %display_debug, true, "message");
        warn!(target: "foo_events", ?display_debug);
        warn!(target: "foo_events", %display_debug);
        warn!(target: "foo_events", ?display_debug, true, "message");
        warn!(target: "foo_events", %foo, true, "message");
        warn!(name: "foo", target: "foo_events", ?foo, true, "message");
        warn!(name: "foo", target: "foo_events", %foo, true, "message");
        warn!(foo = display("foo"), quux = debug(foo));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn error() {
        error!(foo = ?3, bar.baz = %2, quux = false);
        error!(foo = 3, bar.baz = 2, quux = false);
        error!(foo = 3, bar.baz = 3,);
        error!("foo" = 3, bar.baz = 3,);
        error!(foo = 3, "bar.baz" = 3,);
        error!("foo");
        error!("foo: {}", 3);
        error!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
        error!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
        error!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
        error!({ foo = 3, bar.baz = 80 }, "quux");
        error!({ "foo" = 3, "bar.baz" = 80 }, "quux");
        error!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!({ foo = 2, bar.baz = 78 }, "quux");
        error!({ foo = ?2, bar.baz = %78 }, "quux");
        error!(name: "foo", foo = 3, bar.baz = 2, quux = false);
        error!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        error!(name: "foo", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        error!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
        error!(target: "foo_events", foo = 3, bar.baz = 3,);
        error!(target: "foo_events", "foo");
        error!(target: "foo_events", "foo: {}", 3);
        error!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
        error!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
        let foo = 1;
        error!(?foo);
        error!(%foo);
        error!(foo);
        error!("foo" = ?foo);
        error!("foo" = %foo);
        error!("foo" = foo);
        error!(name: "foo", ?foo);
        error!(name: "foo", %foo);
        error!(name: "foo", foo);
        error!(name: "foo", ?foo, true, "message");
        error!(name: "foo", %foo, true, "message");
        error!(name: "foo", foo, true, "message");
        error!(target: "foo_events", ?foo);
        error!(target: "foo_events", %foo);
        error!(target: "foo_events", foo);
        error!(target: "foo_events", ?foo, true, "message");
        error!(target: "foo_events", %foo, true, "message");
        error!(target: "foo_events", foo, true, "message");
        error!(name: "foo", target: "foo_events", ?foo);
        error!(name: "foo", target: "foo_events", %foo);
        error!(name: "foo", target: "foo_events", foo);
        let display_debug = DisplayDebug;
        error!(?display_debug);
        error!(%display_debug);
        error!(name: "foo", ?display_debug);
        error!(name: "foo", %display_debug);
        error!(name: "foo", ?display_debug, true, "message");
        error!(name: "foo", %display_debug, true, "message");
        error!(target: "foo_events", ?display_debug);
        error!(target: "foo_events", %display_debug);
        error!(target: "foo_events", ?display_debug, true, "message");
        error!(target: "foo_events", %foo, true, "message");
        error!(name: "foo", target: "foo_events", ?foo, true, "message");
        error!(name: "foo", target: "foo_events", %foo, true, "message");
        error!(foo = display("foo"), quux = debug(foo));
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn event_root() {
        event!(parent: Option::None, Level::DEBUG, foo = ?3, bar.baz = %2, quux = false);
        event!(
            parent: Option::None,
            Level::DEBUG,
            foo = 3,
            bar.baz = 2,
            quux = false
        );
        event!(
            parent: Option::None,
            Level::DEBUG,
            foo = 3,
            bar.baz = 3,
        );
        event!(parent: Option::None, Level::DEBUG, "foo");
        event!(
            parent: Option::None,
            Level::DEBUG,
            "foo: {}",
            3
        );
        event!(parent: Option::None, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(parent: Option::None, Level::DEBUG, { foo = ?2, bar.baz = %78 }, "quux");
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, foo = 3, bar.baz = 3,);
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, "foo");
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, "foo: {}", 3);
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, foo = 3, bar.baz = 3,);
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, "foo");
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, "foo: {}", 3);
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(name: "foo", target: "foo_events", parent: Option::None, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn trace_root() {
        trace!(parent: Option::None, foo = ?3, bar.baz = %2, quux = false);
        trace!(
            parent: Option::None,
            foo = 3,
            bar.baz = 2,
            quux = false
        );
        trace!(parent: Option::None, foo = 3, bar.baz = 3,);
        trace!(parent: Option::None, "foo");
        trace!(parent: Option::None, "foo: {}", 3);
        trace!(parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        trace!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!(parent: Option::None, { foo = 2, bar.baz = 78 }, "quux");
        trace!(parent: Option::None, { foo = ?2, bar.baz = %78 }, "quux");
        trace!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        trace!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        trace!(target: "foo_events", parent: Option::None, "foo");
        trace!(target: "foo_events", parent: Option::None, "foo: {}", 3);
        trace!(target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        trace!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
        trace!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        trace!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        trace!(name: "foo", target: "foo_events", parent: Option::None, "foo");
        trace!(name: "foo", target: "foo_events", parent: Option::None, "foo: {}", 3);
        trace!(name: "foo", target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        trace!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn debug_root() {
        debug!(parent: Option::None, foo = ?3, bar.baz = %2, quux = false);
        debug!(
            parent: Option::None,
            foo = 3,
            bar.baz = 2,
            quux = false
        );
        debug!(parent: Option::None, foo = 3, bar.baz = 3,);
        debug!(parent: Option::None, "foo");
        debug!(parent: Option::None, "foo: {}", 3);
        debug!(parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        debug!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!(parent: Option::None, { foo = 2, bar.baz = 78 }, "quux");
        debug!(parent: Option::None, { foo = ?2, bar.baz = %78 }, "quux");
        debug!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        debug!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        debug!(target: "foo_events", parent: Option::None, "foo");
        debug!(target: "foo_events", parent: Option::None, "foo: {}", 3);
        debug!(target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        debug!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
        debug!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        debug!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        debug!(name: "foo", target: "foo_events", parent: Option::None, "foo");
        debug!(name: "foo", target: "foo_events", parent: Option::None, "foo: {}", 3);
        debug!(name: "foo", target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        debug!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn info_root() {
        info!(parent: Option::None, foo = ?3, bar.baz = %2, quux = false);
        info!(
            parent: Option::None,
            foo = 3,
            bar.baz = 2,
            quux = false
        );
        info!(parent: Option::None, foo = 3, bar.baz = 3,);
        info!(parent: Option::None, "foo");
        info!(parent: Option::None, "foo: {}", 3);
        info!(parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        info!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!(parent: Option::None, { foo = 2, bar.baz = 78 }, "quux");
        info!(parent: Option::None, { foo = ?2, bar.baz = %78 }, "quux");
        info!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        info!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        info!(target: "foo_events", parent: Option::None, "foo");
        info!(target: "foo_events", parent: Option::None, "foo: {}", 3);
        info!(target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        info!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
        info!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        info!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        info!(name: "foo", target: "foo_events", parent: Option::None, "foo");
        info!(name: "foo", target: "foo_events", parent: Option::None, "foo: {}", 3);
        info!(name: "foo", target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        info!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn warn_root() {
        warn!(parent: Option::None, foo = ?3, bar.baz = %2, quux = false);
        warn!(
            parent: Option::None,
            foo = 3,
            bar.baz = 2,
            quux = false
        );
        warn!(parent: Option::None, foo = 3, bar.baz = 3,);
        warn!(parent: Option::None, "foo");
        warn!(parent: Option::None, "foo: {}", 3);
        warn!(parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        warn!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!(parent: Option::None, { foo = 2, bar.baz = 78 }, "quux");
        warn!(parent: Option::None, { foo = ?2, bar.baz = %78 }, "quux");
        warn!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        warn!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        warn!(target: "foo_events", parent: Option::None, "foo");
        warn!(target: "foo_events", parent: Option::None, "foo: {}", 3);
        warn!(target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        warn!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
        warn!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        warn!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        warn!(name: "foo", target: "foo_events", parent: Option::None, "foo");
        warn!(name: "foo", target: "foo_events", parent: Option::None, "foo: {}", 3);
        warn!(name: "foo", target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        warn!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn error_root() {
        error!(parent: Option::None, foo = ?3, bar.baz = %2, quux = false);
        error!(
            parent: Option::None,
            foo = 3,
            bar.baz = 2,
            quux = false
        );
        error!(parent: Option::None, foo = 3, bar.baz = 3,);
        error!(parent: Option::None, "foo");
        error!(parent: Option::None, "foo: {}", 3);
        error!(parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        error!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!(parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!(parent: Option::None, { foo = 2, bar.baz = 78 }, "quux");
        error!(parent: Option::None, { foo = ?2, bar.baz = %78 }, "quux");
        error!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        error!(target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        error!(target: "foo_events", parent: Option::None, "foo");
        error!(target: "foo_events", parent: Option::None, "foo: {}", 3);
        error!(target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        error!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!(target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
        error!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 2, quux = false);
        error!(name: "foo", target: "foo_events", parent: Option::None, foo = 3, bar.baz = 3,);
        error!(name: "foo", target: "foo_events", parent: Option::None, "foo");
        error!(name: "foo", target: "foo_events", parent: Option::None, "foo: {}", 3);
        error!(name: "foo", target: "foo_events", parent: Option::None, { foo = 3, bar.baz = 80 }, "quux");
        error!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!(name: "foo", target: "foo_events", parent: Option::None, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn event_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        event!(parent: &parent_span, Level::DEBUG, foo = ?3, bar.baz = %2, quux = false);
        event!(parent: &parent_span, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
        event!(parent: &parent_span, Level::DEBUG, foo = 3, bar.baz = 3,);
        event!(parent: &parent_span, Level::DEBUG, "foo");
        event!(parent: &parent_span, Level::DEBUG, "foo: {}", 3);
        event!(parent: &parent_span, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(parent: &parent_span, Level::DEBUG, { foo = ?2, bar.baz = %78 }, "quux");
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, foo = 3, bar.baz = 3,);
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, "foo");
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, "foo: {}", 3);
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, foo = 3, bar.baz = 3,);
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, "foo");
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, "foo: {}", 3);
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        event!(name: "foo", target: "foo_events", parent: &parent_span, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn trace_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        trace!(parent: &parent_span, foo = ?3, bar.baz = %2, quux = false);
        trace!(parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        trace!(parent: &parent_span, foo = 3, bar.baz = 3,);
        trace!(parent: &parent_span, "foo");
        trace!(parent: &parent_span, "foo: {}", 3);
        trace!(parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        trace!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!(parent: &parent_span, { foo = 2, bar.baz = 78 }, "quux");
        trace!(parent: &parent_span, { foo = ?2, bar.baz = %78 }, "quux");
        trace!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        trace!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        trace!(target: "foo_events", parent: &parent_span, "foo");
        trace!(target: "foo_events", parent: &parent_span, "foo: {}", 3);
        trace!(target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        trace!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
        trace!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        trace!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        trace!(name: "foo", target: "foo_events", parent: &parent_span, "foo");
        trace!(name: "foo", target: "foo_events", parent: &parent_span, "foo: {}", 3);
        trace!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        trace!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        trace!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        trace!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn debug_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        debug!(parent: &parent_span, foo = ?3, bar.baz = %2, quux = false);
        debug!(parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        debug!(parent: &parent_span, foo = 3, bar.baz = 3,);
        debug!(parent: &parent_span, "foo");
        debug!(parent: &parent_span, "foo: {}", 3);
        debug!(parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        debug!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!(parent: &parent_span, { foo = 2, bar.baz = 78 }, "quux");
        debug!(parent: &parent_span, { foo = ?2, bar.baz = %78 }, "quux");
        debug!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        debug!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        debug!(target: "foo_events", parent: &parent_span, "foo");
        debug!(target: "foo_events", parent: &parent_span, "foo: {}", 3);
        debug!(target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        debug!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
        debug!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        debug!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        debug!(name: "foo", target: "foo_events", parent: &parent_span, "foo");
        debug!(name: "foo", target: "foo_events", parent: &parent_span, "foo: {}", 3);
        debug!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        debug!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        debug!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        debug!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn info_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        info!(parent: &parent_span, foo = ?3, bar.baz = %2, quux = false);
        info!(parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        info!(parent: &parent_span, foo = 3, bar.baz = 3,);
        info!(parent: &parent_span, "foo");
        info!(parent: &parent_span, "foo: {}", 3);
        info!(parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        info!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!(parent: &parent_span, { foo = 2, bar.baz = 78 }, "quux");
        info!(parent: &parent_span, { foo = ?2, bar.baz = %78 }, "quux");
        info!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        info!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        info!(target: "foo_events", parent: &parent_span, "foo");
        info!(target: "foo_events", parent: &parent_span, "foo: {}", 3);
        info!(target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        info!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
        info!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        info!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        info!(name: "foo", target: "foo_events", parent: &parent_span, "foo");
        info!(name: "foo", target: "foo_events", parent: &parent_span, "foo: {}", 3);
        info!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        info!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        info!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        info!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn warn_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        warn!(parent: &parent_span, foo = ?3, bar.baz = %2, quux = false);
        warn!(parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        warn!(parent: &parent_span, foo = 3, bar.baz = 3,);
        warn!(parent: &parent_span, "foo");
        warn!(parent: &parent_span, "foo: {}", 3);
        warn!(parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        warn!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!(parent: &parent_span, { foo = 2, bar.baz = 78 }, "quux");
        warn!(parent: &parent_span, { foo = ?2, bar.baz = %78 }, "quux");
        warn!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        warn!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        warn!(target: "foo_events", parent: &parent_span, "foo");
        warn!(target: "foo_events", parent: &parent_span, "foo: {}", 3);
        warn!(target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        warn!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
        warn!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        warn!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        warn!(name: "foo", target: "foo_events", parent: &parent_span, "foo");
        warn!(name: "foo", target: "foo_events", parent: &parent_span, "foo: {}", 3);
        warn!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        warn!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        warn!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        warn!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn error_with_parent() {
        let parent_span = span!(Level::TRACE, "im_a_parent!");
        error!(parent: &parent_span, foo = ?3, bar.baz = %2, quux = false);
        error!(parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        error!(parent: &parent_span, foo = 3, bar.baz = 3,);
        error!(parent: &parent_span, "foo");
        error!(parent: &parent_span, "foo: {}", 3);
        error!(parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        error!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!(parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!(parent: &parent_span, { foo = 2, bar.baz = 78 }, "quux");
        error!(parent: &parent_span, { foo = ?2, bar.baz = %78 }, "quux");
        error!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        error!(target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        error!(target: "foo_events", parent: &parent_span, "foo");
        error!(target: "foo_events", parent: &parent_span, "foo: {}", 3);
        error!(target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        error!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!(target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
        error!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 2, quux = false);
        error!(name: "foo", target: "foo_events", parent: &parent_span, foo = 3, bar.baz = 3,);
        error!(name: "foo", target: "foo_events", parent: &parent_span, "foo");
        error!(name: "foo", target: "foo_events", parent: &parent_span, "foo: {}", 3);
        error!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 3, bar.baz = 80 }, "quux");
        error!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
        error!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
        error!(name: "foo", target: "foo_events", parent: &parent_span, { foo = 2, bar.baz = 78, }, "quux");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn field_shorthand_only() {
        #[derive(Debug)]
        struct Position {
            x: f32,
            y: f32,
        }
        let pos = Position {
            x: 3.234,
            y: -1.223,
        };

        trace!(?pos.x, ?pos.y);
        debug!(?pos.x, ?pos.y);
        info!(?pos.x, ?pos.y);
        warn!(?pos.x, ?pos.y);
        error!(?pos.x, ?pos.y);
        event!(Level::TRACE, ?pos.x, ?pos.y);
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn borrow_val_events() {
        // Reproduces https://github.com/tokio-rs/tracing/issues/954
        let mut foo = (String::new(), String::new());
        let zero = &mut foo.0;
        trace!(one = ?foo.1);
        debug!(one = ?foo.1);
        info!(one = ?foo.1);
        warn!(one = ?foo.1);
        error!(one = ?foo.1);
        zero.push_str("hello world");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn borrow_val_spans() {
        // Reproduces https://github.com/tokio-rs/tracing/issues/954
        let mut foo = (String::new(), String::new());
        let zero = &mut foo.0;
        let _trace_span = trace_span!("span", one = ?foo.1);
        let _debug_span = debug_span!("span", one = ?foo.1);
        let _info_span = info_span!("span", one = ?foo.1);
        let _warn_span = warn_span!("span", one = ?foo.1);
        let _error_span = error_span!("span", one = ?foo.1);
        zero.push_str("hello world");
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn callsite_macro_api() {
        // This test should catch any inadvertent breaking changes
        // caused by changes to the macro.
        let _event_callsite = callsite! {
            name: "test callsite",
            kind: Kind::EVENT,
            target: "test target",
            level: Level::TRACE,
            fields: foo, bar,
        };
        let _span_callsite = callsite! {
            name: "test callsite",
            kind: Kind::SPAN,
            level: Level::TRACE,
            fields: foo,
        };
        let _default_span_callsite = callsite! {
            name: "test callsite",
            kind: Kind::SPAN,
            fields: foo,
        };
    }

    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
    #[test]
    fn format_args_already_defined() -> Result<(), TestFailure> {
        // Reproduces: https://github.com/tokio-rs/tracing/issues/2721
        macro_rules! format_args {
            ($i:expr) => {
                $i == 3
            };
        }
        ensure(format_args!(3), "local format_args macro should be used")?;
        event!(Level::DEBUG, "foo: {}", 3);
        trace!("foo: {}", 3);
        debug!("foo: {}", 3);
        info!("foo: {}", 3);
        warn!("foo: {}", 3);
        error!("foo: {}", 3);
        Result::Ok(())
    }
}
