[package]
name = "tracing-attributes"
# When releasing to crates.io:
# - Remove path dependencies
# - Update doc url in README.md.
# - Update CHANGELOG.md.
# - Create "tracing-attributes-0.1.x" git tag.
version = "0.1.31"
authors = [
    "Tokio Contributors <team@tokio.rs>",
    "Eliza Weisman <eliza@buoyant.io>",
    "David Barsky <dbarsky@amazon.com>",
]
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Procedural macro attributes for automatically instrumenting functions.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing", "macro", "instrument", "log"]
license.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[features]

# This feature flag is no longer necessary.
async-await = []

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
tracing = { workspace = true, default-features = true }
tracing-mock = { workspace = true }
tokio-test = { workspace = true }
tracing-subscriber = { workspace = true, default-features = true, features = ["env-filter"] }
tracing-test = { workspace = true }
async-trait = { workspace = true }
strict-test-support = { workspace = true, features = ["trybuild"] }
rustversion = { workspace = true }

[badges]
maintenance = { status = "experimental" }

[lints]
workspace = true
