[package]
name = "tracing-macros"
version.workspace = true
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition.workspace = true
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Macros for emitting trace events
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
tracing = { workspace = true, default-features = true }

[dev-dependencies]
tracing-subscriber = { workspace = true, default-features = true, features = ["env-filter"] }

[badges]
maintenance = { status = "experimental" }

[lints]
workspace = true
