[package]
name = "tracing-mock"
version = "0.1.0-beta.3"
authors = [
    "Eliza Weisman <eliza@buoyant.io>",
    "Hayden Stainsby <hds@caffeineconcepts.com>",
    "Tokio Contributors <team@tokio.rs>",
]
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Utilities for testing `tracing` and crates that uses it.
"""
categories = [
    "development-tools::testing"
]
keywords = [
    "tracing",
    "mock",
    "testing"
]
edition.workspace = true
rust-version.workspace = true

[dependencies]
tracing = { workspace = true, features = ["std", "attributes"] }
tracing-core = { workspace = true }
tracing-subscriber = { workspace = true, features = ["registry"], optional = true }

# Fix minimal-versions; tokio-test fails with otherwise acceptable 0.1.0
tokio-stream = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
