[package]
name = "tracing-appender"
version.workspace = true
authors = [
    "Zeki Sherif <zekshi@amazon.com>",
    "Tokio Contributors <team@tokio.rs>"
]
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Provides utilities for file appenders and making non-blocking writers.
"""
categories = [
    "development-tools::debugging",
    "asynchronous",
]
keywords = ["logging", "tracing", "file-appender", "non-blocking-writer"]
edition.workspace = true
rust-version.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing"] }
parking_lot = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "std"] }

[features]
parking_lot = []

[dev-dependencies]
criterion = { workspace = true }
strict-test-support = { workspace = true }
tracing = { workspace = true, default-features = true }
tempfile = { workspace = true }

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true
