[package]
name = "tracing-futures"
version = "0.2.5"
authors = ["Eliza Weisman <eliza@buoyant.io>", "Tokio Contributors <team@tokio.rs>"]
edition.workspace = true
repository.workspace = true
readme = "README.md"
homepage = "https://tokio.rs"
description = """
Utilities for instrumenting `futures` with `tracing`.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "profiling", "tracing", "futures", "async"]
license.workspace = true
rust-version.workspace = true

[features]
default = ["std-future", "std"]
futures-03 = ["std-future", "futures", "futures-task", "std"]
std-future = ["pin-project-lite"]
std = ["tracing/std"]

[dependencies]
futures = { workspace = true, optional = true, default-features = true }
futures-task = { workspace = true, optional = true }
pin-project-lite = { workspace = true, optional = true }
tracing = { workspace = true }

[dev-dependencies]
futures = { workspace = true, default-features = true }
strict-test-support = { workspace = true }
tokio-test = { workspace = true }
tracing-core = { workspace = true, default-features = true }
tracing-mock = { workspace = true }
tracing-test = { workspace = true }

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
