[package]
name = "tracing-log"
version = "0.2.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition.workspace = true
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Provides compatibility between `tracing` and the `log` crate.
"""
categories = [
    "development-tools::debugging",
    "asynchronous",
]
keywords = ["logging", "tracing", "log"]
license.workspace = true
readme = "README.md"
rust-version.workspace = true

[features]
default = ["log-tracer", "std"]
std = ["log/std"]
log-tracer = []
interest-cache = ["lru", "ahash"]

[dependencies]
tracing-core = { workspace = true, default-features = true }
log = { workspace = true }
once_cell = { workspace = true }
lru = { workspace = true, optional = true }
ahash = { workspace = true, optional = true }

[dev-dependencies]
tracing = { workspace = true, default-features = true }
tracing-subscriber = { workspace = true, default-features = true, features = ["env-filter"] }
criterion = { workspace = true }

[badges]
maintenance = { status = "actively-maintained" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "logging"
harness = false

[lints]
workspace = true
