[package]
name = "tracing-examples"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[features]
default = []

[dev-dependencies]
# tracing crates
tracing = { workspace = true, default-features = true }
tracing-core = { workspace = true, default-features = true }
tracing-error = { workspace = true }
tracing-flame = { workspace = true }
tracing-tower = { workspace = true }
tracing-subscriber = { workspace = true, default-features = true, features = ["json", "env-filter"] }
tracing-futures = { workspace = true, default-features = true, features = ["futures-01"] }
tracing-attributes = { workspace = true }
tracing-serde = { workspace = true }
tracing-appender = { workspace = true }
tracing-journald = { workspace = true }

# serde example
serde_json = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# tower examples
tower = { workspace = true, features = ["full"] }
http = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["tokio", "server-auto", "client-legacy", "service", "http1", "http2"] }
http-body-util = { workspace = true }
rand = { workspace = true }
bytes = { workspace = true }
argh = { workspace = true }

# sloggish example
nu-ansi-term = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }

# inferno example
inferno = { workspace = true }
tempfile = { workspace = true }

# fmt examples
snafu = { workspace = true }
thiserror = { workspace = true }

# env-filter-explorer example
ansi-to-tui = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
parking_lot = { workspace = true }
ratatui-textarea = { workspace = true }

# valuable examples
valuable = { workspace = true, features = ["derive"] }

[target.'cfg(tracing_unstable)'.dependencies]
tracing-core = { workspace = true, default-features = true, features = ["valuable"] }
tracing-subscriber = { workspace = true, default-features = true, features = ["json", "env-filter", "valuable"] }

[lints]
workspace = true
