[package]
name = "tracing-attributes-internal"
version.workspace = true
authors = [
    "Tokio Contributors <team@tokio.rs>",
    "Eliza Weisman <eliza@buoyant.io>",
    "David Barsky <dbarsky@amazon.com>",
]
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Internal implementation engine for the tracing-attributes `#[instrument]` procedural macro.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing", "macro", "instrument", "log"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
strict-test-support = { workspace = true }

[lints]
workspace = true
