[package]
name = "tracing-error"
# When releasing to crates.io:
# - Remove path dependencies
# - Update doc url in README.md.
# - Update CHANGELOG.md.
# - Create "v0.2.x" git tag
version = "0.2.1"
authors = [
    "Eliza Weisman <eliza@buoyant.io>",
    "Jane Lusby <jlusby@yaah.dev>",
    "Tokio Contributors <team@tokio.rs>"
]
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Utilities for enriching errors with `tracing`.
"""
categories = [
    "development-tools::debugging",
    "rust-patterns"
]
keywords = [
    "tracing",
    "error-handling",
    "exception-reporting",
    "backtrace"
]
edition.workspace = true
rust-version.workspace = true

[features]
default = ["traced-error"]
traced-error = []

[dependencies]
tracing-subscriber = { workspace = true, features = ["registry", "fmt"] }
tracing = { workspace = true, features = ["std"] }

[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
