[package]
name = "tracing-flame"
version.workspace = true
authors = [
    "Jane Lusby <jlusby@yaah.dev>",
    "Tokio Contributors <team@tokio.rs>"
]
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage = "https://tokio.rs"
description = """
Tracing layer for creating flamegraphs from span timings
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["tracing", "subscriber", "flamegraph", "profiling"]
rust-version.workspace = true

[features]
default = ["smallvec"]
smallvec = ["tracing-subscriber/smallvec"]

[dependencies]
tracing-subscriber = { workspace = true, features = ["registry", "fmt"] }
tracing = { workspace = true, features = ["std"] }

[dev-dependencies]
strict-test-support = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
